import { describe, expect, it } from "vitest";

import { deserialize, serialize } from "../../src/codec/json.js";
import {
  OutputFormat,
  Resolution,
  VideoCodec,
} from "../../src/gen/transcodely/v1/common_pb.js";
import {
  CreateJobRequest,
  GetJobResponse,
  JobPriority,
  JobStatus,
  OutputSpec,
  VideoVariant,
} from "../../src/gen/transcodely/v1/job_pb.js";
import {
  CreateOriginRequest,
  OriginPermission,
  R2Jurisdiction,
  R2OriginConfig,
  S3Credentials,
} from "../../src/gen/transcodely/v1/origin_pb.js";
import {
  SubtitleFormat,
  SubtitleOperation,
  SubtitleTrack,
} from "../../src/gen/transcodely/v1/subtitles_pb.js";

function decode(bytes: Uint8Array): Record<string, unknown> {
  return JSON.parse(new TextDecoder().decode(bytes)) as Record<string, unknown>;
}

describe("serialize", () => {
  it("emits snake_case fields", () => {
    const req = new CreateJobRequest({ inputUrl: "https://example.com/in.mp4" });
    const obj = decode(serialize(req, CreateJobRequest));
    expect(obj).toHaveProperty("input_url", "https://example.com/in.mp4");
    expect(obj).not.toHaveProperty("inputUrl");
  });

  it("simplifies enum values throughout the message tree", () => {
    const req = new CreateJobRequest({
      inputUrl: "https://example.com/in.mp4",
      priority: JobPriority.PREMIUM,
      outputs: [
        new OutputSpec({
          type: OutputFormat.HLS,
          video: [
            new VideoVariant({
              codec: VideoCodec.H264,
              resolution: Resolution.RESOLUTION_1080P,
            }),
          ],
        }),
      ],
    });
    const obj = decode(serialize(req, CreateJobRequest));
    expect(obj.priority).toBe("premium");
    const outputs = obj.outputs as Array<Record<string, unknown>>;
    expect(outputs[0]!.type).toBe("hls");
    const video = outputs[0]!.video as Array<Record<string, unknown>>;
    expect(video[0]!.codec).toBe("h264");
    expect(video[0]!.resolution).toBe("1080p");
  });
});

describe("AI captions (F5) generate track", () => {
  it("serializes a captions-only generate track + input_video_id to snake_case wire", () => {
    // Retro-caption a hosted video: input_video_id source, one captions-only
    // output (no video[], no type) carrying a single generate track that
    // auto-detects the language.
    const req = new CreateJobRequest({
      inputVideoId: "vid_a1b2c3d4e5f6g7",
      outputs: [
        new OutputSpec({
          subtitleTracks: [
            new SubtitleTrack({
              operation: SubtitleOperation.GENERATE,
              language: "auto",
            }),
          ],
        }),
      ],
    });
    const obj = decode(serialize(req, CreateJobRequest));
    expect(obj).toHaveProperty("input_video_id", "vid_a1b2c3d4e5f6g7");
    expect(obj).not.toHaveProperty("inputVideoId");
    const outputs = obj.outputs as Array<Record<string, unknown>>;
    const tracks = outputs[0]!.subtitle_tracks as Array<Record<string, unknown>>;
    expect(tracks[0]!.operation).toBe("generate");
    expect(tracks[0]!.language).toBe("auto");
  });

  it("deserializes subtitle_results and fees off a job response", () => {
    const payload = new TextEncoder().encode(
      JSON.stringify({
        job: {
          id: "job_t1",
          object: "job",
          status: "completed",
          input_video_id: "vid_a1b2c3d4e5f6g7",
          subtitle_results: [
            {
              output_id: "out_a1b2c3d4e5f6g7",
              operation: "generate",
              format: "webvtt",
              language: "eng",
              label: "English",
              auto_generated: true,
              storage_key: "job_t1/subtitles/out_a1b2c3d4e5f6g7_eng.vtt",
              url: "https://cdn.example.com/job_t1/subtitles/out_a1b2c3d4e5f6g7_eng.vtt",
              transcript_storage_key:
                "job_t1/subtitles/out_a1b2c3d4e5f6g7_eng.transcript.json",
              transcript_url:
                "https://cdn.example.com/job_t1/subtitles/out_a1b2c3d4e5f6g7_eng.transcript.json",
            },
          ],
          fees: [
            {
              fee_type: "captions",
              description: "AI caption generation",
              unit: "source_minute",
              quantity: 10.224667,
              rate: 0.05,
              amount: 0.511233,
              currency: "eur",
            },
          ],
        },
      }),
    );
    const resp = deserialize(payload, GetJobResponse);
    const job = resp.job;
    expect(job).toBeDefined();

    expect(job!.subtitleResults).toHaveLength(1);
    const result = job!.subtitleResults[0]!;
    expect(result.operation).toBe(SubtitleOperation.GENERATE);
    expect(result.format).toBe(SubtitleFormat.WEBVTT);
    expect(result.autoGenerated).toBe(true);
    expect(result.language).toBe("eng");
    expect(result.transcriptStorageKey).not.toBe("");

    expect(job!.fees).toHaveLength(1);
    const fee = job!.fees[0]!;
    expect(fee.feeType).toBe("captions");
    expect(fee.amount).toBeCloseTo(0.511233, 6);
    expect(fee.currency).toBe("eur");
  });
});

describe("deserialize", () => {
  it("expands simplified enums into the right proto integer", () => {
    const payload = new TextEncoder().encode(
      JSON.stringify({
        job: { id: "job_a", status: "processing", priority: "premium" },
      }),
    );
    const resp = deserialize(payload, GetJobResponse);
    expect(resp.job?.id).toBe("job_a");
    expect(resp.job?.status).toBe(JobStatus.PROCESSING);
    expect(resp.job?.priority).toBe(JobPriority.PREMIUM);
  });

  it("accepts the verbose canonical enum form for backward compatibility", () => {
    const payload = new TextEncoder().encode(
      JSON.stringify({ job: { id: "job_a", status: "JOB_STATUS_PROCESSING" } }),
    );
    const resp = deserialize(payload, GetJobResponse);
    expect(resp.job?.status).toBe(JobStatus.PROCESSING);
  });

  it("returns an empty message for empty bytes", () => {
    const resp = deserialize(new Uint8Array(0), GetJobResponse);
    expect(resp.job).toBeUndefined();
  });

  it("ignores unknown fields rather than throwing", () => {
    const payload = new TextEncoder().encode(
      JSON.stringify({ job: { id: "job_a" }, made_up_field: 42 }),
    );
    const resp = deserialize(payload, GetJobResponse);
    expect(resp.job?.id).toBe("job_a");
  });
});

describe("round-trip", () => {
  it("preserves enum values and nested structure across serialize → deserialize", () => {
    const original = new CreateJobRequest({
      inputUrl: "https://example.com/in.mp4",
      outputs: [
        new OutputSpec({
          type: OutputFormat.DASH,
          video: [
            new VideoVariant({
              codec: VideoCodec.AV1,
              resolution: Resolution.RESOLUTION_2160P,
            }),
          ],
        }),
      ],
    });
    const bytes = serialize(original, CreateJobRequest);
    const decoded = deserialize(bytes, CreateJobRequest);
    expect(decoded.inputUrl).toBe(original.inputUrl);
    expect(decoded.outputs[0]?.type).toBe(OutputFormat.DASH);
    expect(decoded.outputs[0]?.video[0]?.codec).toBe(VideoCodec.AV1);
    expect(decoded.outputs[0]?.video[0]?.resolution).toBe(Resolution.RESOLUTION_2160P);
  });
});

describe("R2 origin JSON wire format", () => {
  const ACCOUNT_ID = "0123456789abcdef0123456789abcdef";

  it("serializes the account-id form with snake_case keys and simplified enums", () => {
    const req = new CreateOriginRequest({
      name: "my-r2",
      permissions: [OriginPermission.READ, OriginPermission.WRITE],
      r2: new R2OriginConfig({
        bucket: "media",
        accountId: ACCOUNT_ID,
        jurisdiction: R2Jurisdiction.EU,
        credentials: new S3Credentials({
          accessKeyId: "AKIAEXAMPLE",
          secretAccessKey: "shhh",
        }),
      }),
    });
    const obj = decode(serialize(req, CreateOriginRequest));
    expect(obj.permissions).toEqual(["read", "write"]);
    const r2 = obj.r2 as Record<string, unknown>;
    expect(r2.bucket).toBe("media");
    expect(r2.account_id).toBe(ACCOUNT_ID);
    expect(r2.jurisdiction).toBe("eu");
    expect(r2).not.toHaveProperty("accountId");
    const creds = r2.credentials as Record<string, unknown>;
    expect(creds.access_key_id).toBe("AKIAEXAMPLE");
    expect(creds.secret_access_key).toBe("shhh");
    expect(creds).not.toHaveProperty("accessKeyId");
  });

  it("serializes the endpoint form without account_id or jurisdiction", () => {
    const req = new CreateOriginRequest({
      name: "my-r2-custom",
      permissions: [OriginPermission.READ],
      r2: new R2OriginConfig({
        bucket: "media",
        endpoint: "https://media.example.com",
        credentials: new S3Credentials({
          accessKeyId: "AKIAEXAMPLE",
          secretAccessKey: "shhh",
        }),
      }),
    });
    const obj = decode(serialize(req, CreateOriginRequest));
    const r2 = obj.r2 as Record<string, unknown>;
    expect(r2.endpoint).toBe("https://media.example.com");
    // Unset string scalars are omitted by protojson; unset enums round-trip as
    // the simplified zero-value form (the codec strips the ORIGIN_PROVIDER_/etc
    // prefix unconditionally).
    expect(r2.account_id ?? "").toBe("");
  });

  it("round-trips the account-id form", () => {
    const original = new CreateOriginRequest({
      name: "my-r2",
      permissions: [OriginPermission.READ, OriginPermission.WRITE],
      r2: new R2OriginConfig({
        bucket: "media",
        accountId: ACCOUNT_ID,
        jurisdiction: R2Jurisdiction.FEDRAMP,
        credentials: new S3Credentials({
          accessKeyId: "AKIAEXAMPLE",
          secretAccessKey: "shhh",
        }),
      }),
    });
    const decoded = deserialize(serialize(original, CreateOriginRequest), CreateOriginRequest);
    expect(decoded.name).toBe("my-r2");
    expect(decoded.permissions).toEqual([OriginPermission.READ, OriginPermission.WRITE]);
    expect(decoded.r2?.bucket).toBe("media");
    expect(decoded.r2?.accountId).toBe(ACCOUNT_ID);
    expect(decoded.r2?.jurisdiction).toBe(R2Jurisdiction.FEDRAMP);
    expect(decoded.r2?.credentials?.accessKeyId).toBe("AKIAEXAMPLE");
    expect(decoded.r2?.credentials?.secretAccessKey).toBe("shhh");
  });

  it("round-trips the endpoint form, preserving the optional endpoint string", () => {
    const original = new CreateOriginRequest({
      name: "my-r2-custom",
      permissions: [OriginPermission.READ],
      r2: new R2OriginConfig({
        bucket: "media",
        endpoint: "https://media.example.com",
        credentials: new S3Credentials({
          accessKeyId: "AKIAEXAMPLE",
          secretAccessKey: "shhh",
        }),
      }),
    });
    const decoded = deserialize(serialize(original, CreateOriginRequest), CreateOriginRequest);
    expect(decoded.r2?.endpoint).toBe("https://media.example.com");
    expect(decoded.r2?.accountId).toBe("");
    expect(decoded.r2?.jurisdiction).toBe(R2Jurisdiction.UNSPECIFIED);
  });
});
